// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: configfs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Acl is the access level granted by a ConfigAcl entry. WRITE implies READ.
type Acl int32

const (
	Acl_UNKNOWN_ACL Acl = 0
	Acl_READ        Acl = 1
	Acl_WRITE       Acl = 2
)

// Enum value maps for Acl.
var (
	Acl_name = map[int32]string{
		0: "UNKNOWN_ACL",
		1: "READ",
		2: "WRITE",
	}
	Acl_value = map[string]int32{
		"UNKNOWN_ACL": 0,
		"READ":        1,
		"WRITE":       2,
	}
)

func (x Acl) Enum() *Acl {
	p := new(Acl)
	*p = x
	return p
}

func (x Acl) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Acl) Descriptor() protoreflect.EnumDescriptor {
	return file_configfs_proto_enumTypes[0].Descriptor()
}

func (Acl) Type() protoreflect.EnumType {
	return &file_configfs_proto_enumTypes[0]
}

func (x Acl) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Acl.Descriptor instead.
func (Acl) EnumDescriptor() ([]byte, []int) {
	return file_configfs_proto_rawDescGZIP(), []int{0}
}

// ConfigAcl grants an access level to either a specific Tailscale ACL tag or to
// everyone. A config is accessible at a given level only if at least one of its
// ConfigAcl entries grants that level to the caller; a config with no entries
// is accessible to no one (deny by default).
type ConfigAcl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acl           Acl                    `protobuf:"varint,1,opt,name=acl,proto3,enum=configfs.Acl" json:"acl,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Everyone      bool                   `protobuf:"varint,3,opt,name=everyone,proto3" json:"everyone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigAcl) Reset() {
	*x = ConfigAcl{}
	mi := &file_configfs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigAcl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigAcl) ProtoMessage() {}

func (x *ConfigAcl) ProtoReflect() protoreflect.Message {
	mi := &file_configfs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigAcl.ProtoReflect.Descriptor instead.
func (*ConfigAcl) Descriptor() ([]byte, []int) {
	return file_configfs_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigAcl) GetAcl() Acl {
	if x != nil {
		return x.Acl
	}
	return Acl_UNKNOWN_ACL
}

func (x *ConfigAcl) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ConfigAcl) GetEveryone() bool {
	if x != nil {
		return x.Everyone
	}
	return false
}

type Config struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Content     []byte                 `protobuf:"bytes,3,opt,name=content,proto3,oneof" json:"content,omitempty"`
	ContentSize uint64                 `protobuf:"varint,4,opt,name=content_size,json=contentSize,proto3" json:"content_size,omitempty"`
	Path        string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	Acls        []*ConfigAcl           `protobuf:"bytes,6,rep,name=acls,proto3" json:"acls,omitempty"`
	// Server-maintained: stamped on creation and on every successful update.
	// Values supplied by clients on SetConfig are ignored. Unset on configs
	// stored before timestamps were tracked.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_configfs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_configfs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_configfs_proto_rawDescGZIP(), []int{1}
}

func (x *Config) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Config) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Config) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Config) GetContentSize() uint64 {
	if x != nil {
		return x.ContentSize
	}
	return 0
}

func (x *Config) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Config) GetAcls() []*ConfigAcl {
	if x != nil {
		return x.Acls
	}
	return nil
}

func (x *Config) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Config) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Directory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Directories   []*Directory           `protobuf:"bytes,4,rep,name=directories,proto3" json:"directories,omitempty"`
	Configs       []*Config              `protobuf:"bytes,5,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Directory) Reset() {
	*x = Directory{}
	mi := &file_configfs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Directory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Directory) ProtoMessage() {}

func (x *Directory) ProtoReflect() protoreflect.Message {
	mi := &file_configfs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Directory.ProtoReflect.Descriptor instead.
func (*Directory) Descriptor() ([]byte, []int) {
	return file_configfs_proto_rawDescGZIP(), []int{2}
}

func (x *Directory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Directory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Directory) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Directory) GetDirectories() []*Directory {
	if x != nil {
		return x.Directories
	}
	return nil
}

func (x *Directory) GetConfigs() []*Config {
	if x != nil {
		return x.Configs
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DirectoryId   *string                `protobuf:"bytes,1,opt,name=directory_id,json=directoryId,proto3,oneof" json:"directory_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_configfs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configfs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_configfs_proto_rawDescGZIP(), []int{3}
}

func (x *ListRequest) GetDirectoryId() string {
	if x != nil && x.DirectoryId != nil {
		return *x.DirectoryId
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Top           *Directory             `protobuf:"bytes,1,opt,name=top,proto3" json:"top,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_configfs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configfs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_configfs_proto_rawDescGZIP(), []int{4}
}

func (x *ListResponse) GetTop() *Directory {
	if x != nil {
		return x.Top
	}
	return nil
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_configfs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configfs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_configfs_proto_rawDescGZIP(), []int{5}
}

func (x *GetConfigRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *Config                `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_configfs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configfs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_configfs_proto_rawDescGZIP(), []int{6}
}

func (x *GetConfigResponse) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type SetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *Config                `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigRequest) Reset() {
	*x = SetConfigRequest{}
	mi := &file_configfs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigRequest) ProtoMessage() {}

func (x *SetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configfs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigRequest.ProtoReflect.Descriptor instead.
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return file_configfs_proto_rawDescGZIP(), []int{7}
}

func (x *SetConfigRequest) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type SetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *Config                `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigResponse) Reset() {
	*x = SetConfigResponse{}
	mi := &file_configfs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigResponse) ProtoMessage() {}

func (x *SetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configfs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigResponse.ProtoReflect.Descriptor instead.
func (*SetConfigResponse) Descriptor() ([]byte, []int) {
	return file_configfs_proto_rawDescGZIP(), []int{8}
}

func (x *SetConfigResponse) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type DeleteConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigRequest) Reset() {
	*x = DeleteConfigRequest{}
	mi := &file_configfs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigRequest) ProtoMessage() {}

func (x *DeleteConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configfs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigRequest.ProtoReflect.Descriptor instead.
func (*DeleteConfigRequest) Descriptor() ([]byte, []int) {
	return file_configfs_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteConfigRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigResponse) Reset() {
	*x = DeleteConfigResponse{}
	mi := &file_configfs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigResponse) ProtoMessage() {}

func (x *DeleteConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configfs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigResponse.ProtoReflect.Descriptor instead.
func (*DeleteConfigResponse) Descriptor() ([]byte, []int) {
	return file_configfs_proto_rawDescGZIP(), []int{10}
}

var File_configfs_proto protoreflect.FileDescriptor

const file_configfs_proto_rawDesc = "" +
	"\n" +
	"\x0econfigfs.proto\x12\bconfigfs\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"Z\n" +
	"\tConfigAcl\x12\x1f\n" +
	"\x03acl\x18\x01 \x01(\x0e2\r.configfs.AclR\x03acl\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x1a\n" +
	"\beveryone\x18\x03 \x01(\bR\beveryone\"\xad\x02\n" +
	"\x06Config\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\acontent\x18\x03 \x01(\fH\x00R\acontent\x88\x01\x01\x12!\n" +
	"\fcontent_size\x18\x04 \x01(\x04R\vcontentSize\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12'\n" +
	"\x04acls\x18\x06 \x03(\v2\x13.configfs.ConfigAclR\x04acls\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\n" +
	"\n" +
	"\b_content\"\xa6\x01\n" +
	"\tDirectory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x125\n" +
	"\vdirectories\x18\x04 \x03(\v2\x13.configfs.DirectoryR\vdirectories\x12*\n" +
	"\aconfigs\x18\x05 \x03(\v2\x10.configfs.ConfigR\aconfigs\"F\n" +
	"\vListRequest\x12&\n" +
	"\fdirectory_id\x18\x01 \x01(\tH\x00R\vdirectoryId\x88\x01\x01B\x0f\n" +
	"\r_directory_id\"5\n" +
	"\fListResponse\x12%\n" +
	"\x03top\x18\x01 \x01(\v2\x13.configfs.DirectoryR\x03top\"\"\n" +
	"\x10GetConfigRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x11GetConfigResponse\x12(\n" +
	"\x06config\x18\x01 \x01(\v2\x10.configfs.ConfigR\x06config\"<\n" +
	"\x10SetConfigRequest\x12(\n" +
	"\x06config\x18\x01 \x01(\v2\x10.configfs.ConfigR\x06config\"=\n" +
	"\x11SetConfigResponse\x12(\n" +
	"\x06config\x18\x01 \x01(\v2\x10.configfs.ConfigR\x06config\"%\n" +
	"\x13DeleteConfigRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14DeleteConfigResponse*+\n" +
	"\x03Acl\x12\x0f\n" +
	"\vUNKNOWN_ACL\x10\x00\x12\b\n" +
	"\x04READ\x10\x01\x12\t\n" +
	"\x05WRITE\x10\x022\xaa\x02\n" +
	"\x0eConfigFSServer\x127\n" +
	"\x04List\x12\x15.configfs.ListRequest\x1a\x16.configfs.ListResponse\"\x00\x12F\n" +
	"\tGetConfig\x12\x1a.configfs.GetConfigRequest\x1a\x1b.configfs.GetConfigResponse\"\x00\x12F\n" +
	"\tSetConfig\x12\x1a.configfs.SetConfigRequest\x1a\x1b.configfs.SetConfigResponse\"\x00\x12O\n" +
	"\fDeleteConfig\x12\x1d.configfs.DeleteConfigRequest\x1a\x1e.configfs.DeleteConfigResponse\"\x00B0Z.github.com/davefinster/configfs/internal/protob\x06proto3"

var (
	file_configfs_proto_rawDescOnce sync.Once
	file_configfs_proto_rawDescData []byte
)

func file_configfs_proto_rawDescGZIP() []byte {
	file_configfs_proto_rawDescOnce.Do(func() {
		file_configfs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_configfs_proto_rawDesc), len(file_configfs_proto_rawDesc)))
	})
	return file_configfs_proto_rawDescData
}

var file_configfs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_configfs_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_configfs_proto_goTypes = []any{
	(Acl)(0),                      // 0: configfs.Acl
	(*ConfigAcl)(nil),             // 1: configfs.ConfigAcl
	(*Config)(nil),                // 2: configfs.Config
	(*Directory)(nil),             // 3: configfs.Directory
	(*ListRequest)(nil),           // 4: configfs.ListRequest
	(*ListResponse)(nil),          // 5: configfs.ListResponse
	(*GetConfigRequest)(nil),      // 6: configfs.GetConfigRequest
	(*GetConfigResponse)(nil),     // 7: configfs.GetConfigResponse
	(*SetConfigRequest)(nil),      // 8: configfs.SetConfigRequest
	(*SetConfigResponse)(nil),     // 9: configfs.SetConfigResponse
	(*DeleteConfigRequest)(nil),   // 10: configfs.DeleteConfigRequest
	(*DeleteConfigResponse)(nil),  // 11: configfs.DeleteConfigResponse
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_configfs_proto_depIdxs = []int32{
	0,  // 0: configfs.ConfigAcl.acl:type_name -> configfs.Acl
	1,  // 1: configfs.Config.acls:type_name -> configfs.ConfigAcl
	12, // 2: configfs.Config.created_at:type_name -> google.protobuf.Timestamp
	12, // 3: configfs.Config.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 4: configfs.Directory.directories:type_name -> configfs.Directory
	2,  // 5: configfs.Directory.configs:type_name -> configfs.Config
	3,  // 6: configfs.ListResponse.top:type_name -> configfs.Directory
	2,  // 7: configfs.GetConfigResponse.config:type_name -> configfs.Config
	2,  // 8: configfs.SetConfigRequest.config:type_name -> configfs.Config
	2,  // 9: configfs.SetConfigResponse.config:type_name -> configfs.Config
	4,  // 10: configfs.ConfigFSServer.List:input_type -> configfs.ListRequest
	6,  // 11: configfs.ConfigFSServer.GetConfig:input_type -> configfs.GetConfigRequest
	8,  // 12: configfs.ConfigFSServer.SetConfig:input_type -> configfs.SetConfigRequest
	10, // 13: configfs.ConfigFSServer.DeleteConfig:input_type -> configfs.DeleteConfigRequest
	5,  // 14: configfs.ConfigFSServer.List:output_type -> configfs.ListResponse
	7,  // 15: configfs.ConfigFSServer.GetConfig:output_type -> configfs.GetConfigResponse
	9,  // 16: configfs.ConfigFSServer.SetConfig:output_type -> configfs.SetConfigResponse
	11, // 17: configfs.ConfigFSServer.DeleteConfig:output_type -> configfs.DeleteConfigResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_configfs_proto_init() }
func file_configfs_proto_init() {
	if File_configfs_proto != nil {
		return
	}
	file_configfs_proto_msgTypes[1].OneofWrappers = []any{}
	file_configfs_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_configfs_proto_rawDesc), len(file_configfs_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_configfs_proto_goTypes,
		DependencyIndexes: file_configfs_proto_depIdxs,
		EnumInfos:         file_configfs_proto_enumTypes,
		MessageInfos:      file_configfs_proto_msgTypes,
	}.Build()
	File_configfs_proto = out.File
	file_configfs_proto_goTypes = nil
	file_configfs_proto_depIdxs = nil
}
