FROM golang:alpine
WORKDIR /root/project
# C toolchain required to build with CGO_ENABLED=1.
RUN apk add --no-cache gcc musl-dev
COPY . .
RUN CGO_ENABLED=1 GOOS=linux go build -a -v ./cmd/fs/main.go

FROM alpine:latest
RUN apk add --no-cache curl ca-certificates fuse3 findmnt && mkdir -p /app
COPY --from=0 /root/project/main /app/configfs
RUN chmod +x /app/configfs
ENTRYPOINT ["/app/configfs"]